void Clock(void);
void LatOut(void);
unsigned int8 AbsDiff8(unsigned int8 v1,unsigned int8 v2);
unsigned int16 AbsDiff16(unsigned int16 v1,unsigned int16 v2);
unsigned int8 Diff8(unsigned int8 Lst,unsigned int8 Now);
unsigned int16 Diff16(unsigned int16 Lst,unsigned int16 Now);
unsigned int16 TimeDiff(unsigned int16 LastTime);
void Error(unsigned char ErrorCode);
extern char Hex2Asc[];
int8 absd(int8 v1);
void initUsart(void);
